name: Playwright Tests

on:
  schedule:
    # Run daily at 9 AM IST (3:30 AM UTC)
  - cron: '30 3 * * *'

  # Run daily at 10 AM IST (4:30 AM UTC)
  - cron: '30 4 * * *'

  # Run daily at 1 PM IST (7:30 AM UTC)
  - cron: '30 7 * * *'

  # Run daily at 2 PM IST (8:30 AM UTC)
  - cron: '30 8 * * *'

  workflow_dispatch: {} # Allow manual trigger
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
